### ISSUE TITLE
Server-Error when try to connect with wrong / not existing token. 

### ISSUE THREAD

**Issue by aykborstelmann** [OpenRoberta/openroberta-lab#898]
### Describe the bug
 - When trying to connect with a token which doesn't exist / isn't a valid token (e.g. the connector has not yet connected) the server throws RuntimeException. The frontend therefore reports a `Server-Error`

### To Reproduce
1. Click on `robots > connect`
2. Paste invalid 8 character token e.g. `AJDKKAMA`

### Expected behavior
 - A error message that this token is not yet reported / does not exist

### Stacktrace
```
2020-09-15 13:53:00,302 [qtp494317290-17] session-id=[] user-id=[] robot-name=[] ERROR d.f.i.r.j.r.a.controller.ClientAdmin - Exception. Error ticket: E-1
java.lang.RuntimeException: required property update of SetTokenResponse-object is not set: SetTokenResponse [immutable=true, cmd=setToken, rc=error, message=ORA_TOKEN_SET_ERROR_NO_ROBOT_WAITING, cause=ORA_TOKEN_SET_ERROR_NO_ROBOT_WAITING, parameters=null, initToken=anL6S8Eu--3_, serverTime=1600170780294, serverVersion=4.0.3, robotWait=0, robotBattery=null, robotName=null, robotVersion=null, robotFirmwareName=null, robotSensorvalues=null, robotNepoexitvalue=0, robotState=null, update=0 ]
        at de.fhg.iais.roberta.generated.restEntities.SetTokenResponse.validate(SetTokenResponse.java:163)
        at de.fhg.iais.roberta.generated.restEntities.SetTokenResponse.immutable(SetTokenResponse.java:134)
        at de.fhg.iais.roberta.generated.restEntities.SetTokenResponse.immutable(SetTokenResponse.java:15)
        at de.fhg.iais.roberta.util.UtilForREST.responseWithFrontendInfo(UtilForREST.java:149)
        at de.fhg.iais.roberta.javaServer.restServices.all.controller.ClientAdmin.setToken(ClientAdmin.java:106)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-15 13:53:03,104 [qtp494317290-38] session-id=[1] user-id=[-1] robot-name=[ev3lejosv1] INFO d.fhg.iais.roberta.util.ClientLogger - log entry: [[INFO]] result from server: {"rc":"error","cause":"ORA_SERVER_ERROR","server.version":"4.0.3","message":"ORA_SERVER_ERROR","_version":"1","initToken":"anL6S8Eu--3_","server.time":1600170780303}
2020-09-15 13:53:03,105 [qtp494317290-38] session-id=[1] user-id=[-1] robot-name=[ev3lejosv1] INFO d.fhg.iais.roberta.util.ClientLogger - log entry: [[TIME]] 7 msec: set token 'AJDKKAMA'
```
</details>

**Comment by aykborstelmann** [comment]
Is the property `update` on `SetTokenResponse` still necessary ? Otherwise a fast fix would be to remove the check for this property in `validate`. Actually all error responses in the context of  Tokens don't get the update property set.
